// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehfutvevcymdntemhpfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZnV0dmV2Y3ltZG50ZW1ocGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDk4MjQsImV4cCI6MjA3MTIyNTgyNH0.2LVy-DuDTtJ3CusynIRVeRd_-POpAksr3TxAC1xw170";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});